// Add any additional repositories for your dependencies here.

repositories {
    mavenLocal()
    mavenCentral()
    flatDir {
       dirs 'libs'
    }
    maven {
        name "applecore"
        url "http://www.ryanliptak.com/maven/"
    }
    maven {
        name "chickenbones"
        url "http://chickenbones.net/maven/"
    }
    maven {
        name = "forge"
        url = "http://files.minecraftforge.net/maven"
    }
        maven {
        url "http://dvs1.progwml6.com/files/maven"
    }
    maven {
        name = "Mobius Repo"
        url "http://tehnut.info/maven"
    }
    maven {
        name = "ilexiconn"
        url = "https://maven.mcmoddev.com/"
		}
    maven {
        name = "CurseMaven"
        url = "https://cursemaven.com"
    }
    ivy {
        name "buildcraft"
        artifactPattern "http://www.mod-buildcraft.com/releases/BuildCraft/[revision]/[module]-[revision]-[classifier].[ext]"
    }		
  }