// Add any additional repositories for your dependencies here.

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        forRepositories(fg.repository) // Only add this if you're using ForgeGradle, otherwise remove this line
        filter {
            includeGroup "maven.modrinth"
        }
        flatDir {
            dirs 'libs'
        }
        maven {
            name "applecore"
            url "http://www.ryanliptak.com/maven/"
        }
        maven {
            name "chickenbones"
            url "http://chickenbones.net/maven/"
        }
        maven {
            name = "forge"
            url = "http://files.minecraftforge.net/maven"
        }
        maven {
            url "http://dvs1.progwml6.com/files/maven"
        }
        maven {
            name = "Mobius Repo"
            url "http://tehnut.info/maven"
        }
        maven {
            name = "ilexiconn"
            url = "https://maven.mcmoddev.com/"
        }
        maven {
            name = "CurseMaven"
            url = "https://cursemaven.com"
        }
        ivy {
            name "buildcraft"
            artifactPattern "http://www.mod-buildcraft.com/releases/BuildCraft/[revision]/[module]-[revision]-[classifier].[ext]"
        }
        maven {
            url = "https://maven.minecraftforge.net/"
        }
        gradlePluginPortal() {
            content {
                excludeGroup("org.apache.logging.log4j")
            }
        }
        maven {
            url "https://uncomfortable-fey-midnight145-884fba2b.koyeb.app"
            content {
                includeGroup "curse.fetch"
            }
        }
        maven {
            url "https://jitpack.io"
        }
        maven {
            url "https://beta.cursemaven.com"
        }
    }
}
